---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-gradle
    tag: "latest"

inputs:
- name: ola-nativos

run:
  path: ola-nativos/ci/tasks/run-unit-tests.sh
