groups:
- name: main
  jobs:
  - unit-tests
  - build-artifact
  - deploy

resources:
- name: git-repo
  type: git
  source:
    uri: {{GIT_REPO}}
    branch: master
    private_key: {{GIT_PRIVATE_KEY}}

- name: deploy-prod-app
  type: cf
  source:
    api: {{PWS_API}}
    organization: {{PWS_ORG}}
    username: {{PWS_USER}}
    password: {{PWS_PASSWORD}}
    skip_cert_check: true
    space: {{PWS_SPACE}}

- name: release-candidate
  type: github-release
  source:
    owner: {{GIT_USER}}
    repository: {{GIT_RELEASE_REPO}}
    access_token: {{GIT_ACCESS_TOKEN}}

jobs:
  - name: unit-tests
    plan:
    - get: git-repo
      trigger: true
    - task: unit
      file: git-repo/ci/tasks/unit.yml

  - name: build-artifact
    serial: true
    plan:
    - get: git-repo
      passed: [unit-tests]
      trigger: true
    - task: build-artifact
      file: git-repo/ci/tasks/build-artifact.yml
      timeout: 5m
      params:
        base_name: ola-nativos
    - put: release-candidate
      params:
        name: git-repo/ci/name
        body: git-repo/ci/release-body
        globs:
          - artifact-dir/ola-nativos*.jar
    - put: git-repo
      params:
        repository: git-repo

  - name: deploy
    plan:
    - get: release-candidate
      passed: [build-artifact]
    - get: git-repo
      passed: [build-artifact]
    - put: deploy-prod-app
      params:
        manifest: gitrepo/manifest.yml
        current_app_name: ola-nativos
        path: release-candidate/ola-nativos*.jar
