groups:
- name: main
  jobs:
  - unit-tests
  - build-and-deploy

resources:
- name: git-repo
  type: git
  source:
    uri: {{GIT_REPO}}
    branch: master
    private_key: {{GIT_PRIVATE_KEY}}

- name: deploy-prod-app
  type: cf
  source:
    api: {{PWS_API}}
    organization: {{PWS_ORG}}
    username: {{PWS_USER}}
    password: {{PWS_PASSWORD}}
    skip_cert_check: true
    space: {{PWS_SPACE}}

- name: version
  type: semver
  source:
    driver: git
    uri: {{GIT_REPO}}
    branch: version
    file: version
    private_key: {{GIT_PRIVATE_KEY}}
    initial_version: 1.0.0

jobs:
  - name: unit-tests
    plan:
    - get: git-repo
      trigger: true
    - task: unit
      file: git-repo/ci/tasks/unit.yml

  - name: build-and-deploy
    serial_groups: [version]
    serial: true
    plan:
    - get: git-repo
      passed: [unit-tests]
      trigger: true
    - get: version
      params: { pre: rc }
    - task: build-artifact
      file: git-repo/ci/tasks/build-artifact.yml
      timeout: 5m
      params:
        base_name: ola-nativos
    - put: deploy-prod-app
      params:
        manifest: git-repo/manifest.yml
        current_app_name: ola-nativos
        path: artifact-dir/ola-nativos-1.0.0-rc.1.jar
